onplates/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from onplates import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),

    (r'^media/(.*)$', 'django.views.static.serve',
     {'document_root': settings.MEDIA_ROOT}),
    url(r'^placa-interna/(?P<place_id>[\w_-]+)/$', 'core.views.placeIntern', name='interna'),
    url(r'^$', 'core.views.homepage', name='homepage'),
)

core/models.py
from datetime import datetime
from django.db import models
from django.template.defaultfilters import default


class UserProfile(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name


class Institution(models.Model):
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    uf = models.CharField(max_length=50)
    country = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name


class Forming(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(null=True, blank=True)
    img_perfil = models.ImageField(upload_to='img_perfil')

    def __unicode__(self):
        return self.name


class Place(models.Model):
    team_name = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)
    course = models.ForeignKey(Course)
    institution = models.ForeignKey(Institution)
    user_profile = models.ForeignKey(UserProfile)
    formings = models.ManyToManyField(Forming, null=True, blank=True)

    def __unicode__(self):
        return self.team_name


class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    place = models.ForeignKey(Place)

    def __unicode__(self):
        return self.name


class Photo(models.Model):
    description = models.TextField(null=True, blank=True)
    img = models.ImageField(upload_to="photos")
    date = models.DateTimeField(auto_now_add=True)
    album = models.ForeignKey(Album)


class Video(models.Model):
    place = models.ForeignKey(Place)
    name = models.CharField(max_length=50)
    description = models.TextField()
    url = models.TextField(blank=False, null=False)
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name


class TextBlock(models.Model):
    place = models.ForeignKey(Place)
    name = models.CharField(max_length=100)
    text_area = models.TextField()
    author = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name


class PhotoBlock(models.Model):
    place = models.ForeignKey(Place)
    name = models.CharField(max_length=50)
    description = models.TextField()
    img = models.ImageField(upload_to='img_blocks')

    def __unicode__(self):
        return self.name

core/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.template import RequestContext
from core.models import Place


def homepage(request):
    places = Place.objects.all()
    return render_to_response('placas.html', locals(), context_instance=RequestContext(request))


def placeIntern(request, place_id):
    place = Place.objects.get(pk=place_id)
    return render_to_response('home.html', locals(), context_instance=RequestContext(request))

templates/home.html
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>WOnPlate</title>

  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="stylesheets/foundation.css">
  -->

  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/foundation.css">
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/style.css">
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/jquery.fancybox.css">

  <script src="{{ MEDIA_URL }}javascripts/modernizr.foundation.js"></script>

</head>
<body>
  <!-- Navigation -->


  <header>
    <div class="row">
      <div class="four columns">
        <a href="{% url "core.views.homepage" %}"><h1>OnPlates</h1></a>

      </div>

      <div class="three columns">
        <div class="row collapse" id="search-form">
          <div class="ten mobile-three columns">
            <input type="text" placeholder="Faça sua busca aqui"/>
          </div>
          <div class="two mobile-one columns">
            <span class="postfix"><a href="" class="lupa"></a></span>
          </div>
        </div>

      </div>


      <div class="four columns">
        <a class="small button right" href="/">Login</a>
      </div>

    </div>
  </header>



  <!-- End Navigation -->

  <section id="placa-name">
    <div class="row">
      <div class="twelve columns">
        <h1 class="text-center title">{{ place.team_name }}</h1>
        <h3 class="text-center subtitle">{{ place.course.name }}</h3>
      </div>
    </div>
  </section>

  <section id="board-img">
    <div class="row">
      <div class="twelve columns">
      <div class="bg-placa scrollbar">
        <ul class="connected sortable list-board ">
          {% for student in place.formings.all %}
          <li>
              <div class="card">
                <a href="modal-card" data-reveal-id="modal-card">
                    <img src="{{ MEDIA_URL }}{{ student.img_perfil }}" />
                    <h5>{{ student.name }}</h5>
                </a>
              </div>
          </li>
          {% endfor %}
        </ul>
      </div>
      </div>
    </div>
  </section>

  <section id="thanks">
    <div class="row">
      <div class="twelve columns">
        {% for blockText in place.textblock_set.all %}
        <h3>{{ blockText.name }}</h3>
        <p>{{ blockText.text_area }}</p>
        {% endfor %}
      </div>
    </div>
  </section>

  <section id="picture">
    <div class="row">
      <div class="twelve columns">
          {% for album in place.album_set.all %}
            <h3>Álbuns</h3>
            <h5>{{ album.name }}</h5>
              {% for photos in album.photo_set.all %}
                <div class="card album">
                  <a class="fancybox" rel="gallery1" href="{{ MEDIA_URL }}{{ photos.img }}">
                      <img src="{{ MEDIA_URL }}{{ photos.img }}" alt="" />
                  </a>
                </div>
            {% endfor %}
        {% endfor %}
      </div>
    </div>
  </section>

   <section id="video">
    <div class="row">
      <div class="twelve columns">
        <h3>Videos</h3>
        {% for videos in place.video_set.all %}
        <div class="card album">
          <a href="/">
              {{ videos.url|safe }}
              <h5>{{ videos.name }}</h5>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>





  <!-- Included JS Files (Compressed) -->

   <script src="{{ MEDIA_URL }}javascripts/jquery.js"></script>
   <script src="{{ MEDIA_URL }}javascripts/foundation.min.js"></script>

  <!-- Initialize JS Plugins -->
  <script src="{{ MEDIA_URL }}javascripts/app.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/sortable.js"></script>
  <script type="text/javascript" src="{{ MEDIA_URL }}javascripts/jquery.fancybox.pack.js"></script>
  <script type="text/javascript" src="{{ MEDIA_URL }}javascripts/jquery.fancybox.js"></script>
  <script type="text/javascript" src="{{ MEDIA_URL }}javascripts/jquery.mousewheel-3.0.6.pack.js"></script>

  <script>
    $(function() {
      $('.sortable').sortable();
      $('.handles').sortable({
        handle: 'span'
      });
      $('.connected').sortable({
        connectWith: '.connected'
      });
      $('.exclude').sortable({
        items: ':not(.disabled)'
      });
    });

    $(document).ready(function() {
      $("#buttonForModal").click(function() {
        $("#modal-card-").reveal();

      });
    });

    $(document).ready(function() {
        $(".fancybox").fancybox({
            openEffect	: 'none',
            closeEffect	: 'none'
        });
    });
  </script>
</body>
</html>

templates/placas.html
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8" />

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width" />

    <title>WOnPlate</title>

    <!-- Included CSS Files (Uncompressed) -->
    <!--
    <link rel="stylesheet" href="stylesheets/foundation.css">
    -->

    <!-- Included CSS Files (Compressed) -->
    <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/foundation.css">
    <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/style.css">
    <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/jquery.fancybox.css">

    <script src="{{ MEDIA_URL }}javascripts/modernizr.foundation.js"></script>

</head>
<body>
<!-- Navigation -->


<header>
    <div class="row">
        <div class="four columns">
            <a href="{% url "core.views.homepage" %}"><h1>OnPlates</h1></a>

        </div>

        <div class="three columns">
            <div class="row collapse" id="search-form">
                <div class="ten mobile-three columns">
                    <input type="text" placeholder="Faça sua busca aqui"/>
                </div>
                <div class="two mobile-one columns">
                    <span class="postfix"><a href="" class="lupa"></a></span>
                </div>
            </div>

        </div>


        <div class="four columns">
            <a class="small button right" href="/">Login</a>
        </div>

    </div>
</header>



<!-- End Navigation -->

<section id="placa-name">
    <div class="row">
        {% for place in places %}
        <a href="{% url "core.views.placeIntern" place.id %}">
        <div class="twelve columns">
            <div class="linha">
                {% for student in place.formings.all|slice:":4" %}
                        <div class="card">
                                <img style="float: left" src="{{ MEDIA_URL }}{{ student.img_perfil }}" />
                        </div>
                {% endfor %}
                <h1 class="text-center title">{{ place.team_name }}</h1>
                <h3 class="text-center subtitle">{{ place.course.name }}</h3>
            </div>
        </div>
        </a>
        {% endfor %}
    </div>
</section>


<!-- Included JS Files (Compressed) -->

<script src="{{ MEDIA_URL }}javascripts/foundation.min.js"></script>

<!-- Initialize JS Plugins -->
<script src="{{ MEDIA_URL }}javascripts/app.js"></script>
<script src="{{ MEDIA_URL }}javascripts/sortable.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}javascripts/jquery.fancybox.pack.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}javascripts/jquery.fancybox.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}javascripts/jquery.mousewheel-3.0.6.pack.js"></script>

<script>
    $(function() {
        $('.sortable').sortable();
        $('.handles').sortable({
            handle: 'span'
        });
        $('.connected').sortable({
            connectWith: '.connected'
        });
        $('.exclude').sortable({
            items: ':not(.disabled)'
        });
    });

    $(document).ready(function() {
        $("#buttonForModal").click(function() {
            $("#modal-card-").reveal();

        });
    });

    $(document).ready(function() {
        $(".fancybox").fancybox({
            openEffect  : 'none',
            closeEffect : 'none'
        });
    });
</script>
</body>
</html>